### ISSUE TITLE
Dependency bump + other maintenance work

### ISSUE THREAD

**Issue by fdocr** [neovintage/kemal-session-redis#10]
Hi @neovintage, first of all thank you for the work you did to put this shard together.

I've been playing a bit with the code and wanted to ask if you're still welcoming contributions. I did some stuff in my fork like merge #7, replaced the deprecated `JSON.mapping` macro, bumped dependencies, setup CI on GitHub actions and a small fix on the specs. Things seem to work alright after my tinkering.

If you were to merge #7 I would be happy to then push my stuff upstream (here). I would appreciate a code review from your end in case anything seems off to your eye though.

If you're not available to work on this repo anymore that's something I can understand and respect. In that case I'd feel good about continuing to maintain my fork, were I would keep your original authorship and all. Another alternative is to help you maintain this one (as a collaborator), but I wanted to reach out before moving forward with either alternative.

**Comment by neovintage** [comment]
Hey @fdocr! Thanks for opening an issue. ❤️

I'm open to contributions. I usually check in on issues and PRs once every 2 - 3 weeks. I'll review the PR tomorrow and let you know what I find.

**Comment by fdocr** [comment]
That's awesome, thank you for getting back to me @neovintage.

I just sent #11 as a start 🙂

**Comment by neovintage** [comment]
The main branch has been updated. It should work for kemal-session 1.0 and all of the versions of crystal we've got in the matrix builds. 

I need to tag a new release but is there anything I missed?

**Comment by fdocr** [comment]
Thanks for all this @neovintage!

Question: How do you feel about using `version: ~> 1.0` for the `kemal-session` dependency in the project's `shard.yml` instead of `branch: master`?

I'm running into a conflict on a project of mine because I'm also using [kemal-csrf](https://github.com/kemalcr/kemal-csrf), which [pins `kemal-session` to version 1.x](https://github.com/kemalcr/kemal-csrf/blob/master/shard.yml#L7) and this shard pins the master branch (screenshot below).

<img width="883" alt="Screen Shot 2022-09-06 at 19 04 04" src="https://user-images.githubusercontent.com/6045239/188766210-7b28568f-2c87-4778-90e4-9a6e2ff8def0.png">

That was an easy tweak and I tested it on my fork. It seems to work well, so I went ahead and sent it as a PR (#13) too. Since `kemal-session` is on `1.0` I think it would be safe to go down that route 🙂

**Comment by fdocr** [comment]
Also, really minor detail for after you tag the new release: Might be worth it to bump the README installation instructions to match the latest version. But other than the above everything looks golden!

**EDIT:** Also noticing the `version` field from `shard.yml` should probably be bumped along with the version file (screenshot above reads version `0.3.0` despite the version file has `0.5.0`), for when the new release goes out 😅

**Comment by neovintage** [comment]
Merged #13 and took care of the version in `shard.yml`. I tagged a new release too! 

https://github.com/neovintage/kemal-session-redis/releases/tag/1.0.0

I think we're good and can close this issue. 😄

**Comment by fdocr** [comment]
Sweet! I did ran into this other problem as I tried to reference this shard using `version: ~> 1.0.0` on a separate project:

<img width="399" alt="Screen Shot 2022-09-08 at 18 37 41" src="https://user-images.githubusercontent.com/6045239/189249340-71d2a788-153d-49a8-bd11-04f62254720c.png">

The [inline VERSION](https://github.com/neovintage/kemal-session-redis/blob/master/src/kemal-session-redis/version.cr#L2) wasn't bumped and I believe this is the cause of the error.

Just submitted #15 that _I hope_ would fix this issue + any future version bumps 🙂

**Comment by neovintage** [comment]
I merged the last fix for the inline version (i can't believe I forgot that part). I published a patch release `1.0.1`. I think this should be good now. 

I'll close this issue for now. If the problem is still there, feel free to reopen this issue. 

Thanks for all your help @fdocr
